### ISSUE TITLE
Account notification e-mail should come from a valid sender

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/pip#1]
The notification e-mail for a new account has the FROM clause "PIP.com@tis.bz.it", which is an invalid e-mail address.

**Comment by ohnewein** [comment]
The e-mail contains a link to the platform. But the link gets identified as scam by Thunderbird.

This is because the link text is a URL "http://projectideas.tis.bz.it/" but the link points to a very different URL. Can this be changed?

**Comment by bertolla** [comment]
I've used sendgrid as an smtp server for the first deployment(cause it works always). I will ask Stefano for the config details to use our in house smtp server.
Sendgrid took the link and changed it, probably to monitor us ._.

**Comment by bertolla** [comment]
Ok localy it works. What should the from mail be?

**Comment by ohnewein** [comment]
For now we can user open (at) tis.bz.it
