### ISSUE TITLE
Max count of characters in Activities and Measures is to restrictive

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/pip#10]
Has there to be a limit of characters?

I would really like to add much more information and there are project ideas I am not able to describe all WPs, already.

**Comment by bertolla** [comment]
This was a wanted limit in the main project, it can be removed or changed but is not a bug.
In my own opinion text fields should be limited and should only consist of the main information.
There should be existing documents which already describe every Work package in Detail and these should be added as Attachments.
