### ISSUE TITLE
After logout the user is still able to use the app. As a ?new? user?

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/pip#2]
After I was logged in, I used the Logou menu item. Instead of being presented with a login screen, I have been redirected to the home page (projects) and am still able to use the portal. Even to change progile data to some unknown user.

**Comment by ohnewein** [comment]
I am using Firefox 28.0 on Ubuntu

**Comment by ohnewein** [comment]
Btw. I am not able to find a way to login, now :-(

**Comment by ohnewein** [comment]
I have been able to get to the login screen, Restarting Firefox and forcing a refresh of the site. Seams to be some caching problem involved.

**Comment by bertolla** [comment]
The user that logged  out can not perform any actions. It's angular which performs the caching. I changed the url on logout to /login.
