### ISSUE TITLE
/favicon.ico not found error

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/pip#7]
After logging in, I often get an error message and have to manually edit the URL in the browser, because it is directed to a favicon.ico file, which does not exist on the server.

**Comment by bertolla** [comment]
merged with master and should be working now

**Comment by ohnewein** [comment]
After login I get a badly formatted page, because it is pointing to /partials/index.html To get useful data, I have to change the URL in the browser to point to /

**Comment by bertolla** [comment]
Wasn't able to reproduce the issue (chrome, firefox). It might be a caching problem, but if not we might need to have a look at it together.

**Comment by ohnewein** [comment]
Browser cache and refreshes seam to be some issues on this app. But in general the favicon bug looks fixed.
