### ISSUE TITLE
Markup in Project Idea

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/pip#9]
Through Markup the user can create a Layout of the content, which has titles bigger than the section Titles of the project ideas layout.

I see 2 possible solutions:
1) the css is changed to align all heights of titles and texts
2) the section titles get formatted more vidibly. Lets say with a horizontal line and the section title centered in the line.

![screenshot from 2016-02-04 10 51 49](https://cloud.githubusercontent.com/assets/414797/12811528/57ce4c1c-cb2d-11e5-9f9c-4ed4f6b67c8c.png)

**Comment by bertolla** [comment]
This will change in the next release:
- section titles will be more pronounced
- headers of sections will be less pronounced
- better padding and more margin between sections
